packages:
  - '.'

onlyBuiltDependencies:
  - '@tsparticles/engine'
  - '@tsparticles/basic'
  - '@tsparticles/move-base'
  - '@tsparticles/shape-circle'
  - '@tsparticles/updater-color'
  - '@tsparticles/updater-opacity'
  - '@tsparticles/updater-out-modes'
  - '@tsparticles/updater-size'
  - 'tsparticles'
  - sharp

shamefully-hoist: true
