<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            ['slug' => 'vence-pro', 'title' => 'Vence Pro 360 — Seguimiento Documental de Flotas', 'description' => 'Sistema multiplataforma (Web, PWA, APK, EXE + Chatbot WhatsApp) para seguimiento documental de flotas de representantes de ventas en Postobón. Construido con PHP, JavaScript, MySQL, Docker e IA. Procesa flujos críticos para +600 clientes activos.', 'images' => ['/images/projects/vence-pro.png', '/images/projects/vence-pro-2.png', '/images/projects/vence-pro-3.png'], 'technologies' => ['PHP', 'JavaScript', 'MySQL', 'Docker', 'IA'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Postobón / Gaseosas Lux S.A.S.', 'platforms' => ['web', 'pwa', 'apk', 'exe'], 'year' => 2025, 'featured' => true],
            ['slug' => 'luxcontrol', 'title' => 'LuxControl — Control de Acceso de Personal y Equipos', 'description' => 'Aplicación Web/PWA/EXE para control de entrada y salida de personal y equipos en planta. Integra flujos administrativos con SAP (anticipos, viáticos, facturas) y Webdox (contratos digitales) automatizando la gestión de RRHH.', 'images' => ['/images/projects/luxcontrol.png', '/images/projects/luxcontrol-2.png'], 'technologies' => ['JavaScript', 'PHP', 'MySQL'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Postobón / Gaseosas Lux S.A.S.', 'platforms' => ['web', 'pwa', 'exe'], 'year' => 2025, 'featured' => true],
            ['slug' => 'luna-sofia', 'title' => 'Luna Sofía — ERP Distribuciones (+600 clientes)', 'description' => 'ERP completo (React + Laravel) con +50 módulos: cartera, comisiones, pedidos, inventarios (+1.700 productos). Auditoría de rutas con Google Maps API, gestión multi-rol (Admin, Vendedor, Repartidor, Cliente) y Chatbot IA. Ventas >$114M mensuales.', 'images' => ['/images/projects/luna-sofia.png', '/images/projects/luna-sofia-2.png', '/images/projects/luna-sofia-3.png'], 'technologies' => ['React', 'Laravel', 'MySQL', 'Google Maps', 'IA'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Luna Sofía Distribuciones', 'platforms' => ['web', 'apk'], 'year' => 2025, 'featured' => true],
            ['slug' => 'sgi-fermar', 'title' => 'SGI FERMAR — Sistema de Gestión Integral', 'description' => 'Sistema de gestión integral con PHP, JavaScript, MySQL y arquitectura MVC. Ciclo completo: requerimientos, modelado relacional, APIs REST y despliegue en producción con Docker. Módulo Python/IA para análisis.', 'images' => ['/images/projects/sgi-fermar.png', '/images/projects/sgi-fermar-2.png'], 'technologies' => ['PHP', 'JavaScript', 'MySQL', 'Python', 'Docker'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Montajes y Construcciones Fermar S.A.S.', 'platforms' => ['web'], 'year' => 2026, 'featured' => true],
            ['slug' => 'cotizapp', 'title' => 'CotizaApp — Cotizaciones e Inventario', 'description' => 'Aplicación web para cotizaciones e inventariado con PHP, JavaScript/React y MySQL. Frontend con Bootstrap y despliegue corporativo. Control de versiones con Git y buenas prácticas de documentación.', 'images' => ['/images/projects/cotizapp.png', '/images/projects/cotizapp-2.png'], 'technologies' => ['PHP', 'React', 'MySQL', 'Bootstrap'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Tecniconstrucciones BR S.A.S.', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'novedapp', 'title' => 'Novedapp — Reporte de Novedades Operativas', 'description' => 'Plataforma para el reporte de novedades operativas en campo con PHP, Vue.js y MySQL. Integración de APIs REST, validaciones con POO y despliegue en servidor de producción.', 'images' => ['/images/projects/novedapp.png', '/images/projects/novedapp-2.png'], 'technologies' => ['PHP', 'Vue.js', 'MySQL'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'JPLUMSER Service', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'fleet-app', 'title' => 'Fleet App — Gestión de Flotas Logísticas', 'description' => 'Aplicación web para gestión integral de flotas logísticas con React + Laravel + MySQL. Auditoría de rutas en tiempo real con Google Maps API y panel multi-rol.', 'images' => ['/images/projects/fleet-app.png', '/images/projects/fleet-app-2.png'], 'technologies' => ['React', 'Laravel', 'MySQL', 'Google Maps'], 'github_private' => true, 'demo_url' => 'https://fleet.app-dev.icu', 'demo_private' => false, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'EasyLogística', 'platforms' => ['web'], 'year' => 2025, 'featured' => true],
            ['slug' => 'wellmapp', 'title' => 'Wellmapp — Geolocalizador de Pozos Petroleros', 'description' => 'App móvil (APK + iOS) offline para geolocalización de +15.000 pozos petroleros y reporte de incidentes en campo. Construida con Python, Flask y geolocalización GPS para uso exclusivo de Ecopetrol.', 'images' => ['/images/wellmap.png', '/images/wellmap.png'], 'technologies' => ['Python', 'Flask', 'HTML5', 'CSS3'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Ecopetrol', 'platforms' => ['apk', 'ios'], 'year' => 2024],
            ['slug' => 'web-tecniconstrucciones', 'title' => 'Web Tecniconstrucciones — Sitio Corporativo', 'description' => 'Página web corporativa de Tecniconstrucciones BR con React, Bootstrap y Chatbot IA integrado para atención de clientes potenciales.', 'images' => ['/images/projects/tecniconstrucciones.png', '/images/projects/tecniconstrucciones-2.png'], 'technologies' => ['React', 'Bootstrap', 'IA'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => false, 'category' => 'empresarial', 'client' => 'Tecniconstrucciones BR S.A.S.', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'printflow', 'title' => 'PrintFlow — Plataforma de Gestión de Impresión', 'description' => 'Plataforma multiplataforma (Web, PWA, APK, EXE) para gestión de flujos de impresión y pedidos. Construida con JavaScript, PHP y MySQL.', 'images' => ['/images/projects/printflow.png', '/images/projects/printflow-2.png'], 'technologies' => ['JavaScript', 'PHP', 'MySQL'], 'github_url' => 'https://github.com/Juan-Campo-developer/printflow', 'github_private' => false, 'demo_url' => 'https://printflow.app-dev.icu', 'demo_private' => false, 'demo_soon' => false, 'category' => 'personal', 'platforms' => ['web', 'apk', 'pwa', 'exe'], 'year' => 2025, 'featured' => true],
            ['slug' => 'situr', 'title' => 'Situr — Sistema Turístico Inteligente', 'description' => 'Plataforma web turística con HTML, CSS y Python que incluye un Chatbot IA para recomendaciones personalizadas de destinos y rutas.', 'images' => ['/images/projects/situr.png', '/images/projects/situr-2.png'], 'technologies' => ['HTML5', 'CSS3', 'Python', 'IA'], 'github_url' => 'https://github.com/Juan-Campo-developer/situr', 'github_private' => false, 'demo_private' => true, 'demo_soon' => true, 'category' => 'personal', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'microgreens', 'title' => 'Microgreens — Cultivos Hidropónicos', 'description' => 'Sitio web educativo y de gestión para cultivos de microgreens hidropónicos. Construido con HTML, CSS y Flask (Python).', 'images' => ['/images/projects/microgreens.png', '/images/projects/microgreens-2.png'], 'technologies' => ['HTML5', 'CSS3', 'Flask', 'Python'], 'github_url' => 'https://github.com/Juan-Campo-developer/microgreens', 'github_private' => false, 'demo_private' => true, 'demo_soon' => true, 'category' => 'personal', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'adsonary', 'title' => 'Adsonary — Diccionario Técnico de Software', 'description' => 'Diccionario web para aprendices de desarrollo, con búsqueda en tiempo real de términos y ejemplos prácticos. Construido con Node.js, Express y JavaScript usando un CSV como base de datos.', 'images' => ['/images/adsonary.png', '/images/adsonary.png'], 'technologies' => ['Node.js', 'Express', 'JavaScript'], 'github_url' => 'https://github.com/Juan-Campo-developer/Adsonary-Diccionario-Tecnico-de-Software', 'github_private' => false, 'demo_url' => 'https://adsonary.onrender.com/', 'demo_private' => false, 'demo_soon' => false, 'category' => 'personal', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'mallapp', 'title' => 'Mallapp — Directorio Comercial de Centros Comerciales', 'description' => 'Aplicación web para directorio interactivo de tiendas, promociones y eventos en centros comerciales. Búsqueda por categorías y mapa interno.', 'images' => ['/images/projects/mallapp.png', '/images/projects/mallapp-2.png'], 'technologies' => ['JavaScript', 'PHP', 'MySQL'], 'github_private' => false, 'demo_private' => true, 'demo_soon' => true, 'category' => 'personal', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'votaciones-sena', 'title' => 'Sistema de Votaciones SENA', 'description' => 'Sistema web de votaciones electrónicas para representantes de aprendices del SENA. Autenticación segura, conteo en tiempo real y resultados auditables.', 'images' => ['/images/projects/votaciones-sena.png', '/images/projects/votaciones-sena-2.png'], 'technologies' => ['PHP', 'JavaScript', 'MySQL', 'HTML5'], 'github_url' => 'https://github.com/Juan-Campo-developer/votaciones-sena', 'github_private' => false, 'demo_private' => true, 'demo_soon' => false, 'category' => 'academico', 'client' => 'SENA — CIDT Barrancabermeja', 'platforms' => ['web'], 'year' => 2024],
            ['slug' => 'tentaapp', 'title' => 'Tentaapp — Experimento Mobile', 'description' => 'Aplicación móvil experimental construida como APK para probar flujos de UX y arquitectura cliente-servidor ligera.', 'images' => ['/images/projects/tentaapp.png', '/images/projects/tentaapp-2.png'], 'technologies' => ['JavaScript', 'Node.js'], 'github_private' => true, 'demo_private' => true, 'demo_soon' => true, 'category' => 'experimental', 'platforms' => ['apk'], 'year' => 2024],
        ];

        foreach ($projects as $index => $project) {
            Project::updateOrCreate(
                ['slug' => $project['slug']],
                $project + ['status' => 'published', 'sort_order' => $index + 1]
            );
        }
    }
}
